%YAML:1.0

#common parameters
imu: 1
num_of_cam: 2  # 1 or 2
GPS: 0

imu_topic: "/dji_sdk_1/dji_sdk/imu"
image0_topic: "/stereo/left/image"
image1_topic: "/stereo/right/image" 
output_path: "/home/dji/swarm_log_lastest/"

cam0_calib:  "left.yaml"
cam1_calib:  "right.yaml"
image_width: 640
image_height: 512
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -2.9860226902523879e-02, -2.8067796287838554e-02,
       9.9915992997161096e-01, 4.6963138092731754e-02,
       1.0514758816861815e-02, -9.9955918140447131e-01,
       -2.7764774752316951e-02, 6.8684558718123540e-02,
       9.9949877773629781e-01, 9.6768632091223817e-03,
       3.0142190067725672e-02, 6.8963620641618900e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ -3.7239244263084670e-02, -1.1705084897619311e-02,
       9.9923782438129016e-01, 4.6745388845793621e-02,
       2.8673542642719770e-02, -9.9953220042073521e-01,
       -1.0639937706573274e-02, -6.3144421863824324e-02,
       9.9889492272161984e-01, 2.8255465128416361e-02,
       3.7557450011234561e-02, 6.9739683892232771e-02, 0., 0., 0., 1. ]

#body_T_cam0: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ 0.0, 0.0, 1.0, 0.0633,
#        0.0, -1.0, 0.0, 0.0762,
#        1.0, 0.0, 0.0, 0.0567,
#        0.0, 0.0, 0.0, 1.0 ]
#
#body_T_cam1: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ 0., 0., 1., 0.0620,
#           0., -1., 0., -0.060,
#           1., 0., 0., 0.0581,
#            0., 0., 0., 1. ]

multiple_thread: 2

#feature traker paprameters
max_cnt: 100            # max feature number in feature tracking
min_dist: 40            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.02  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805       # gravity magnitude

#loop closure parameters
loop_closure: 0                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/dji/swarm_log_lastest/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                          # online estimate time offset between camera and imu
#td: -0.002375                              # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
td: 0.0063                              # -0.029 for USB2.0, -0.002375 for usb 3.0

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
